
a = "aa"
[section]
b = "bb"
[[array]]
c = "c1"
[[array]]
c = "c2"

[metadata.VALUE]
other = true
123456 = 0.5
value.txt = "text"
value.'l\i\t' = "lit\eral"
value.dec = 123
value.bin = 0b110
value.oct = 0o707
value.hex = 0xF6F
value.123 = false